#this is the name of the workflow

name: My first workflow

on:

  # any push will trigger this workflow

 push:
    branches: 
        - 'v[0-9]+.[0-9]+'
    paths-ignore:
        - '**/#NORUN*'

jobs:

  my_first_ci:

    #from this point onwards is ubuntu

    runs-on: ubuntu-latest
    
    steps:

      - name: Run Trivy vulnerability scanner in repo mode
        id: Trivy_scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          output: 'trivy-results.txt'
          severity: 'HIGH'
          exit-code: 1


      - name: Upload Trivy scan results to Slack
        uses: MeilCli/slack-upload-file@v3
        if: failure()
        with:
            slack_token: ${{ secrets.SLACKTOCKEN }}
            channel_id: ${{ secrets.CHANNELID }}
            file_type: 'text'
            file_name: 'trivy-results.txt'
            initial_comment: 'post by slack-upload-file'


      - name: Slack Notification  
        uses: rtCamp/action-slack-notify@v2
        env: 
          SLACK_WEBHOOK: ${{ secrets.HUANG_YONGFEI }}

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_CHANNEL: general
            SLACK_COLOR: ${{ job.status }} 
            SLACK_ICON: https://github.com/rtCamp.png?size=48
            SLACK_TITLE: Information
            SLACK_MESSAGE: |
              *Name*:HuangYongFei
              *Matriculation number*:A028597
              *Email*:E1221783@u.nus.edu
              *Repository*:https://github.com/${{ github.action_repository }}/CICDWorkShop/tree/v1.3
              *Docker Hub URL*:https://hub.docker.com/repository/docker/watari1018/cicd_workshop1/general
 
            SLACK_USERNAME: Huang YongFei
            SLACK_WEBHOOK: ${{ secrets.HUANG_YONGFEI }}


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3


      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DONAME }}
          password: ${{ secrets.DOPASSWORD }}


      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: watari1018/cicd_workshop1:${{github.sha}}

      - name: cosign-installer
        uses: sigstore/cosign-installer@v3.1.2
        with: 
            cosign-release: v2.2.0

        # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable


      - name: Sign image with a key
        run: |
         cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${TAGS}"
        env:
         TAGS: watari1018/cicd_workshop1:${{github.sha}}
         COSIGN_PRIVATE_KEY: ${{ secrets.CONSIGNPRIVATEKEY }}
         COSIGN_PASSWORD: ${{ secrets.SECRETCOSIGN }}
         
      - name: Checkout code
        uses: actions/checkout@v3
    
     

      
          